name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.12.29
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  injectable: ^2.1.1
  path: ^1.8.2
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
